version: '3.8'

services:

  fastapi-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      - database-test
    # command: bash -c 'while !</dev/tcp/database-test/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8004'
    entrypoint: /app/entrypoint_test.sh
    expose:
      - 8004
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-test.rule=Host(`fastapi.localhost`)"
      - "traefik.http.services.fastapi-test.loadbalancer.server.port=8004"
      - "traefik.http.routers.fastapi-test.entrypoints=web"

  database-test:
    build:
      context: ./backend/db
      dockerfile: Dockerfile.test
    expose:
      - 5432
    env_file:
      - .env.test

  traefik-test:
    image: traefik:v2.9.6
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
