version: "3.8"

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    container_name: fastapi
    ports:
      - 5678:5678
      - 8004:8004
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - DATABASE_TEST_BACKEND_URL=${DATABASE_TEST_BACKEND_URL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_TLS=${MAIL_TLS}
      - MAIL_SSL=${MAIL_SSL}
      - BASE_URL_API=${BASE_URL_API}
      - BASE_URL_FRONTEND=${BASE_URL_FRONTEND}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - ./backend:/app
    command: [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen
        0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port
        8004",
      ]
    depends_on:
      - database

  database:
    build:
      context: ./backend/db
      dockerfile: Dockerfile.dev
    container_name: database
    init: true
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data: null
  pgadmin-data: null
