version: "3.8"

services:
  traefik:
    image: traefik:v2.9.6
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=noreply@gebroedersvroege.nl"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    env_file:
      - .env.prod
    depends_on:
      - fastapi
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.rule=Host(`superleuk.gebroedersvroege.nl`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  nuxtui:
    build:
      context: ./nuxtui
      dockerfile: Dockerfile
    container_name: "nuxtui"
    env_file:
      - .env.prod
    depends_on:
      - fastapi
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.rule=Host(`app.gebroedersvroege.nl`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"


  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: "fastapi"
    env_file:
      - .env.prod
    depends_on:
      - database
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004
    expose:
      - 8004
    volumes:
      - ./backend:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`superleuk.gebroedersvroege.nl`) && PathPrefix(`/api`)"
      - "traefik.http.services.fastap.loadbalancer.server.port=8004"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"

  database:
    build:
      context: ./backend/db
      dockerfile: Dockerfile.prod
    container_name: "database"
    expose:
      - 5432
    env_file:
      - .env.prod
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.gebroedersvroege.nl`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"



volumes:
  db-data:
  pgadmin-data:
