FROM node:18.15-alpine as develop-stage
WORKDIR /app
COPY package*.json ./
RUN yarn global add @quasar/cli \
    && npm i -g eslint
COPY . .


# build stage
FROM develop-stage as build-stage
RUN yarn \
    && yarn lint \
    && API_URL=http://api.localhost/api quasar build -m pwa


# production stage
FROM nginx:1.23.4-alpine as production-stage
COPY --from=build-stage /app/dist/pwa /usr/share/nginx/html
