# https://medium.com/towards-data-engineering/quick-setup-configure-superset-with-docker-a5cca3992b28

FROM apache/superset:latest

USER root

RUN pip install psycopg2

COPY superset-init.sh /app/superset-init.sh

RUN sed -i 's/\r$//' /app/superset-init.sh

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

USER superset

ENTRYPOINT [ "/app/superset-init.sh" ]
