// This file is auto-generated by @hey-api/openapi-ts

export type AddRoleToUserRequest = {
    user_id: number;
    role_id: number;
};

export type AddressResponse = {
    street?: string;
    number?: string;
    postal_code?: string;
    city?: string;
    country?: string;
};

export type AllowedUserRequest = {
    email: string;
};

export type AllowedUserResponse = {
    id: number;
    created_at: string;
    last_modified_at: string;
    email: string;
};

export type Body_auth_login = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CreateRoleRequest = {
    name: string;
    description: string;
};

/**
 * HTTP error schema to be used when an `HTTPException` is thrown.
 */
export type HTTPError = {
    detail: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KlauwScoreBase = {
    koenummer: string;
    behandeldatum: string;
    notatie: string;
};

export type RegisterUserRequest = {
    first_name: string;
    last_name: string;
    email: string;
    password: string;
};

export type ReleaseRequest = {
    from_date: string;
    to_date: string;
    user_id: number;
};

export type RemoveRoleFromUserRequest = {
    user_id: number;
    role_id: number;
};

export type ResetPassword = {
    token: string;
    password: string;
};

export type ResourceResponse = {
    id: number;
    groupId: number;
    title: string;
};

export type RoleInUserResponse = {
    id: number;
    name: string;
    description: string;
};

export type RoleResponse = {
    id: number;
    created_at: string;
    last_modified_at: string;
    name: string;
    description: string;
};

export type SuccessResponse = {
    detail: string;
    data?: unknown | null;
};

export type TokenResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

export type TokenSchema = {
    token?: string | null;
    refresh_token?: string | null;
};

export type UpdateAddressRequest = {
    street?: string | null;
    number?: string | null;
    postal_code?: string | null;
    city?: string | null;
    country?: string | null;
};

export type UpdateUserRequest = {
    first_name: string | null;
    last_name: string | null;
    email: string | null;
    telephone_number: string | null;
    date_of_birth: string | null;
};

export type VakantieCreateSchemaForUserAsAdmin = {
    start_date: string;
    end_date: string;
    user_id: number;
};

export type VakantieRequest = {
    start_date: string;
    end_date: string;
};

export type VakantieResponse = {
    id: number;
    start_date: string;
    end_date: string;
};

export type VakantiesForCalendarResponse = {
    id: number;
    start: string;
    end: string;
    resourceId: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WeekTotals = {
    month: string;
    hours: number;
    milkings: number;
};

export type WorkingHoursRequest = {
    id?: number | null;
    date: string;
    hours: number;
    milkings?: number | null;
    description: string;
    submitted?: boolean | null;
};

export type WorkingHoursResponse = {
    id: number;
    date: string;
    hours: number;
    milkings: number;
    description: string;
    submitted: boolean;
};

export type WorkingHoursWeekOverviewResponse = {
    year: number;
    week: number;
    week_start: string;
    week_end: string;
    working_hours: Array<WorkingHoursResponse>;
    sum_hours: number;
    sum_milkings: number;
    submitted: boolean;
};

export type app__models__pydantic_models__auth__UserResponse = {
    id: number;
    created_at: string;
    last_modified_at: string;
    first_name: string;
    last_name: string;
    date_of_birth: string | null;
    email: string;
    telephone_number: string | null;
    is_active: boolean;
    confirmation: string | null;
    roles: Array<RoleResponse> | null;
};

export type app__models__pydantic_models__users__UserResponse = {
    id: number;
    first_name: string | null;
    last_name: string | null;
    email: string;
    telephone_number: string | null;
    date_of_birth: string | null;
    is_active: boolean;
    roles: Array<RoleInUserResponse>;
    address: AddressResponse | null;
};

export type $OpenApiTs = {
    '/auth/register': {
        post: {
            req: {
                requestBody: RegisterUserRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                201: SuccessResponse;
                /**
                 * Gebruiker bestaat al of email niet bevoegd
                 */
                400: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * Interne serverfout bij het aanmaken van gebruiker
                 */
                500: unknown;
            };
        };
    };
    '/auth/activate_account': {
        post: {
            req: {
                requestBody: TokenSchema;
            };
            res: {
                /**
                 * Account geactiveerd
                 */
                200: SuccessResponse;
                /**
                 * Bad Request
                 */
                400: HTTPError;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
                /**
                 * Internal Server Error
                 */
                500: HTTPError;
            };
        };
    };
    '/auth/resent_activation_token/{email}': {
        get: {
            req: {
                email: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/auth/login': {
        post: {
            req: {
                formData: Body_auth_login;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: TokenResponse;
                /**
                 * Niet geautoriseerd
                 */
                401: HTTPError;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/auth/refresh': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: TokenResponse;
                /**
                 * Ongeldige token scope of gebruiker niet gevonden
                 */
                400: unknown;
                /**
                 * Refresh token ontbreekt of is verlopen
                 */
                403: unknown;
            };
        };
    };
    '/auth/forgot_password/{email}': {
        get: {
            req: {
                email: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/auth/reset_password': {
        post: {
            req: {
                requestBody: ResetPassword;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/auth/logout': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/allowed_users/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<AllowedUserResponse>;
            };
        };
        post: {
            req: {
                requestBody: AllowedUserRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                201: AllowedUserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/allowed_users/{id}': {
        get: {
            req: {
                id: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: AllowedUserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: {
                id: number;
                requestBody: AllowedUserRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                id: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__auth__UserResponse;
            };
        };
        put: {
            req: {
                requestBody: UpdateUserRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__auth__UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/working_hours/all': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<WorkingHoursResponse>;
            };
        };
    };
    '/working_hours/between_dates/': {
        get: {
            req: {
                fromDate: string;
                toDate: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<WorkingHoursResponse>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/working_hours/year_overview/': {
        get: {
            req: {
                year: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<WeekTotals>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/working_hours/week_overview/': {
        get: {
            req: {
                fromDate: string;
                toDate: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<WorkingHoursWeekOverviewResponse>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/working_hours/': {
        put: {
            req: {
                requestBody: WorkingHoursRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/vakanties/resources': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ResourceResponse>;
            };
        };
    };
    '/vakanties/': {
        post: {
            req: {
                requestBody: VakantieRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/vakanties/admin/add_vakantie_for_user': {
        post: {
            req: {
                requestBody: VakantieCreateSchemaForUserAsAdmin;
                responseCode?: unknown;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: VakantieResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/vakanties/all_for_me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VakantieResponse>;
            };
        };
    };
    '/vakanties/all': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VakantiesForCalendarResponse>;
            };
        };
    };
    '/vakanties/all_between_dates': {
        get: {
            req: {
                endDate: string;
                startDate: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VakantieResponse>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/vakanties/{vakantie_id}': {
        delete: {
            req: {
                vakantieId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/working_hours/year_overview/': {
        get: {
            req: {
                userId: number;
                year: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/working_hours/week_overview/': {
        get: {
            req: {
                fromDate: string;
                toDate: string;
                userId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<WorkingHoursWeekOverviewResponse>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/working_hours/release': {
        put: {
            req: {
                requestBody: ReleaseRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/roles/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<RoleResponse>;
            };
        };
        post: {
            req: {
                requestBody: CreateRoleRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: RoleResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/roles/{role_id}': {
        delete: {
            req: {
                roleId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/users/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<app__models__pydantic_models__users__UserResponse>;
            };
        };
    };
    '/admin/users/{user_id}': {
        get: {
            req: {
                userId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__users__UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: {
                requestBody: UpdateUserRequest;
                userId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__users__UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                userId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/users/add_role_to_user/': {
        post: {
            req: {
                requestBody: AddRoleToUserRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__users__UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/users/remove_role_from_user/': {
        delete: {
            req: {
                requestBody: RemoveRoleFromUserRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__users__UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/address/{user_id}': {
        put: {
            req: {
                requestBody: UpdateAddressRequest;
                userId: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: app__models__pydantic_models__auth__UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/klauwscore/': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
        get: {
            req: {
                behandeldatumEnd?: string;
                behandeldatumStart?: string;
                koenummer?: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<KlauwScoreBase>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/admin/klauwscore/csv': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};