// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgGridVue: typeof import('ag-grid-vue3')['AgGridVue']
    CardLeftIcon: typeof import('./components/cards/CardLeftIcon.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Grid: typeof import('./components/grid.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoringenGrid: typeof import('./components/StoringenGrid.vue')['default']
  }
}
